#!/bin/bash

count=1

if [ $# -ne 1 ]
then
	echo "Enter the first 3 octets of an IP address!"
	exit 1
fi
 
while [ $count -lt 255 ] 
do
	ping $1.$count -c 1 | awk "/^64 bytes/" | cut -d " " -f 4 | sed 's/://' &  
	((count++))
done

sleep 1
echo "Sweep completed!"
