#!/bin/bash

release_file=/etc/os-release

error_log=/var/log/updater_errors.log

check_exit_status(){
	if [ $? -ne 0 ] 
	then
		echo "An error has occurred, please check $error_log file."
	fi
}

if grep -q "Arch" $release_file
then
	sudo pacman -Syu --noconfirm 2>>$error_log 
	check_exit_status
fi

if grep -q "Debian" $release_file || grep -q "Ubuntu" $release_file
then
	sudo apt update 2>>$error_log
	check_exit_status
	
	sudo apt -y dist-upgrade 2>>$error_log
	check_exit_status
fi
